name: Generate Documentation

env:
  SPACEMAN_DMM_VERSION: suite-1.10

permissions:
  contents: read

on:
  push:
    branches:
    - dev
  workflow_dispatch:


jobs:
  preflight:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: paths-filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: .github/workflow-config/preflight-filters.yml
    outputs:
      dm: ${{ steps.filter.outputs.dm }}

  generate_documentation:
    permissions:
      contents: write # required to push the doc commit
    runs-on: ubuntu-22.04
    needs: preflight
    if: |
      (needs.preflight.outputs.dm == 'true') &&
      !contains(github.event.head_commit.message, '[ci skip]')
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Setup Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ~/spaceman_dmm/${{ env.SPACEMAN_DMM_VERSION }}
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install dmdoc
        run:  scripts/install-spaceman-dmm.sh dmdoc
      - name: Generate documentation
        run: |
          ~/dmdoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4a3abc783e1a24aeb44c16e869ad83caf6b4cc23
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dmdoc
          target-folder: docs
          clean: true
