name: Run Tests

env:
  BYOND_MAJOR: "516"
  BYOND_MINOR: "1667"
  BYOND_SOURCE: "https://indm.dev/byond" # Canonical: https://www.byond.com/download/build
  SPACEMAN_DMM_VERSION: suite-1.10

permissions:
  contents: read

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  preflight:
    name: Check Test Requirements
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: .github/workflow-config/preflight-filters.yml
    outputs:
      dm: ${{ steps.filter.outputs.dm }}

  dreamchecker:
    name: Dreamchecker
    runs-on: ubuntu-22.04
    needs:
    - preflight
    if: needs.preflight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: ~/spaceman_dmm/${{ env.SPACEMAN_DMM_VERSION }}
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install Dreamchecker
        run:  scripts/install-spaceman-dmm.sh dreamchecker
      - name: Run Dreamchecker
        run: ~/dreamchecker
      - name: Report Failure
        if: ${{ failure() }}
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        run: |
          wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
          chmod +x send.sh
          ./send.sh failure $WEBHOOK_URL

  install_byond:
    name: Install BYOND
    runs-on: ubuntu-22.04
    needs:
    - preflight
    if: needs.preflight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Check Cache
        uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809
        id: check
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install Byond
        if: ${{ !steps.check.outputs.cache-hit }}
        run: |
          sudo apt-get update
          sudo apt-get -y install file unzip
          chmod +x test/install-byond.sh
          test/install-byond.sh
      - name: Save Cache
        if: ${{ !steps.check.outputs.cache-hit && success() }}
        uses: actions/cache/save@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}

  code_health:
    name: Code Health & Style
    runs-on: ubuntu-22.04
    needs:
    - preflight
    - dreamchecker
    - install_byond
    if: needs.preflight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y uchardet
      - name: Run Tests
        env:
          TEST: CODE
        run: test/run-test.sh
      - name: Report Failure
        if: ${{ failure() }}
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        run: |
          wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
          chmod +x send.sh
          ./send.sh failure $WEBHOOK_URL

  map_example:
    name: Unit Tests - Example Map
    runs-on: ubuntu-22.04
    needs:
    - preflight
    - dreamchecker
    - install_byond
    if: needs.preflight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libcurl4:i386
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: example
        run: test/run-test.sh
      - name: Report Failure
        if: ${{ failure() }}
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        run: |
          wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
          chmod +x send.sh
          ./send.sh failure $WEBHOOK_URL

  map_torch:
    name: Unit Tests - Torch Map
    runs-on: ubuntu-22.04
    needs:
    - preflight
    - dreamchecker
    - install_byond
    if: needs.preflight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libcurl4:i386
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: torch
        run: test/run-test.sh
      - name: Report Failure
        if: ${{ failure() }}
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        run: |
          wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
          chmod +x send.sh
          ./send.sh failure $WEBHOOK_URL

  map_dynamic:
    name: Unit Tests - Sites & Ruins
    runs-on: ubuntu-22.04
    needs:
    - preflight
    - dreamchecker
    - install_byond
    if: needs.preflight.outputs.dm == 'true'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libcurl4:i386
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: away_sites_testing
        run: test/run-test.sh
      - name: Report Failure
        if: ${{ failure() }}
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        run: |
          wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
          chmod +x send.sh
          ./send.sh failure $WEBHOOK_URL
